---

- name: configure newsyslog for service
  lineinfile:
    path: "{{ newsyslog_conf_file }}"
    regexp: "^<include> {{ service_newsyslog_dir }}/"
    line: "<include> {{ service_newsyslog_dir }}/[!.]*.conf"
  when: ansible_distribution == 'FreeBSD'
